import { orderLineItems, orders } from '../../../src/database/schema';
import {
  api,
  createLifecycleHarness,
  orderBody,
  type LifecycleHarness,
} from '../../support/http-fixtures';

/**
 * User Story 1, and FR-011 to FR-027. The happy path, which is where money
 * enters the system and therefore where price capture, exact-integer
 * arithmetic, and all-or-nothing writing have to hold.
 */
describe('placing an order', () => {
  let harness: LifecycleHarness;

  beforeAll(async () => {
    harness = await createLifecycleHarness();
  });

  afterAll(async () => {
    await harness.close();
  });

  it('stores the order and returns it, priced from the catalog', async () => {
    const catalog = harness.catalog();

    const response = await api(harness).create(
      orderBody(catalog, [
        { productId: catalog.productId, quantity: 3 },
        { productId: catalog.otherProductId, quantity: 1 },
      ]),
    );

    expect(response.status).toBe(201);
    expect(response.headers['location']).toBe(`/api/v1/orders/${response.body.id}`);

    expect(response.body).toMatchObject({
      customerId: catalog.customerId,
      status: 'pending',
    });

    // FR-022: one server-derived value written to both.
    expect(response.body.createdAtUs).toBe(response.body.updatedAtUs);
    expect(Number.isSafeInteger(response.body.createdAtUs)).toBe(true);
    expect(response.body.createdAtUs).toBeGreaterThan(0);

    // FR-024: the total is the exact sum of what the database computed.
    const lines = response.body.lines as { lineTotalMinor: number }[];
    expect(response.body.totalMinor).toBe(
      lines.reduce((sum, line) => sum + line.lineTotalMinor, 0),
    );
  });

  /** FR-018, FR-019: the caller cannot influence either, because it never supplies them. */
  it('captures the price and description from the catalog, not from the request', async () => {
    const catalog = harness.catalog();
    const [product] = harness.connection.sqlite
      .prepare('SELECT name, unit_price_minor AS price FROM products WHERE id = ?')
      .all(catalog.productId) as { name: string; price: number }[];

    const response = await api(harness).create(
      orderBody(catalog, [{ productId: catalog.productId, quantity: 4 }]),
    );

    expect(response.status).toBe(201);
    expect(response.body.lines[0]).toMatchObject({
      productId: catalog.productId,
      productDescription: product!.name,
      unitPriceMinor: product!.price,
      quantity: 4,
      lineTotalMinor: product!.price * 4,
    });
  });

  /** FR-026: permitted, and each line priced and totalled independently. */
  it('permits the same product on several lines', async () => {
    const catalog = harness.catalog();

    const response = await api(harness).create(
      orderBody(catalog, [
        { productId: catalog.productId, quantity: 2 },
        { productId: catalog.productId, quantity: 5 },
      ]),
    );

    expect(response.status).toBe(201);
    expect(response.body.lines).toHaveLength(2);
    expect(response.body.lines[0].productId).toBe(catalog.productId);
    expect(response.body.lines[1].productId).toBe(catalog.productId);
    expect(response.body.totalMinor).toBe(
      response.body.lines[0].lineTotalMinor + response.body.lines[1].lineTotalMinor,
    );
  });

  /**
   * FR-020 and contract obligation O1. Checked against storage rather than
   * against the response, because the response is generated by the same code
   * path that would be wrong.
   */
  it('writes the order and every line as one unit', async () => {
    const catalog = harness.catalog();

    const response = await api(harness).create(
      orderBody(catalog, [
        { productId: catalog.productId, quantity: 1 },
        { productId: catalog.otherProductId, quantity: 2 },
        { productId: catalog.productId, quantity: 3 },
      ]),
    );

    const storedOrders = harness.connection.db.select().from(orders).all();
    const storedLines = harness.connection.db.select().from(orderLineItems).all();

    expect(storedOrders).toHaveLength(1);
    expect(storedOrders[0]!.id).toBe(response.body.id);
    expect(storedLines).toHaveLength(3);
    expect(storedLines.every((line) => line.orderId === response.body.id)).toBe(true);
  });

  it('accepts the largest permitted order', async () => {
    const catalog = harness.catalog();

    const response = await api(harness).create(
      orderBody(
        catalog,
        Array.from({ length: 100 }, () => ({ productId: catalog.productId, quantity: 1 })),
      ),
    );

    expect(response.status).toBe(201);
    expect(response.body.lines).toHaveLength(100);
  });

  /** FR-095 */
  it('records the creation with its correlation identifier', async () => {
    const catalog = harness.catalog();

    const response = await api(harness).create(orderBody(catalog), {
      'X-Correlation-Id': 'creation-record-check',
    });

    // Matched on the correlation identifier, not the order identifier: log lines
    // accumulate across the file while row ids restart at 1 after each rebuild.
    const record = harness
      .records('order.created')
      .find((entry) => entry.correlationId === 'creation-record-check');

    expect(record).toMatchObject({
      correlationId: 'creation-record-check',
      orderId: response.body.id,
      lineCount: 1,
      totalMinor: response.body.totalMinor,
    });
  });
});
